env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - prettier
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions:
    - '.vue'
plugins:
  - '@typescript-eslint'
  - vue
rules: {}
ignorePatterns:
  - vite.config.ts
